const FIRST_STEP = 1;

const LAST_STEP = 4;

const SUBMIT_STEP = 4;

const SUBMIT_INDEX = SUBMIT_STEP - 1;

const TEXTAREA_ROWS = 4;

const SERVICE_LIST_1 = ['EDU', 'LEVEL', 'DEVTH'];
const SERVICE_LIST_2 = ['IDE', 'EXP', ''];

const EXPECT_LIST = ['1', '2', '3', '4'];
export default {
	FIRST_STEP,
	LAST_STEP,
	SUBMIT_STEP,
	SUBMIT_INDEX,
	TEXTAREA_ROWS,
	SERVICE_LIST_1,
	SERVICE_LIST_2,
	EXPECT_LIST,
};
